### ISSUE TITLE
sbt testOnly/runMain psp.tests.Benchmark2 produces java.lang.NullPointerException

### ISSUE THREAD

**Issue by mallman** [paulp/psp-std#136]
```
> testOnly/runMain psp.tests.Benchmark2
[warn] Credentials file /Users/msa/.bintray/.credentials does not exist
[warn] Credentials file /Users/msa/.bintray/.credentials does not exist
[warn] Credentials file /Users/msa/.bintray/.credentials does not exist
[info] Running psp.tests.Benchmark2 
[error] (run-main-2) java.lang.NullPointerException
java.lang.NullPointerException
	at psp.std.Vec.copyLeft(Vec.scala:431)
	at psp.std.Vec.cleanRightEdge(Vec.scala:444)
	at psp.std.Vec.dropBack0(Vec.scala:498)
	at psp.std.Vec.take(Vec.scala:121)
	at psp.tests.Benchmark2$.b1(Benchmark2.scala:14)
	at psp.tests.Benchmark2$$anonfun$psp$tests$Benchmark2$$do2$1$2.apply$mcJ$sp(Benchmark2.scala:40)
	at psp.tests.Benchmark2$$anonfun$psp$tests$Benchmark2$$do2$1$2.apply(Benchmark2.scala:40)
	at psp.tests.Benchmark2$$anonfun$psp$tests$Benchmark2$$do2$1$2.apply(Benchmark2.scala:40)
	at psp.std.StdAll.timed(StdPackage.scala:93)
	at psp.tests.Benchmark2$.psp$tests$Benchmark2$$do2$1(Benchmark2.scala:40)
	at psp.tests.Benchmark2$$anonfun$main$1.apply$mcVI$sp(Benchmark2.scala:43)
	at psp.tests.Benchmark2$$anonfun$main$1.apply(Benchmark2.scala:42)
	at psp.tests.Benchmark2$$anonfun$main$1.apply(Benchmark2.scala:42)
	at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:52)
	at scala.Function1$class.apply$mcVI$sp(Function1.scala:36)
	at scala.runtime.AbstractFunction1.apply$mcVI$sp(AbstractFunction1.scala:12)
	at psp.std.lowlevel.ll$.foreachConsecutive(LowLevel.scala:23)
	at psp.std.Consecutive.foreach(Consecutive.scala:20)
	at psp.tests.Benchmark2$.main(Benchmark2.scala:42)
	at psp.tests.Benchmark2.main(Benchmark2.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
[trace] Stack trace suppressed: run last testOnly/compile:runMain for the full output.
java.lang.RuntimeException: Nonzero exit code: 1
	at scala.sys.package$.error(package.scala:27)
[trace] Stack trace suppressed: run last testOnly/compile:runMain for the full output.
[error] (testOnly/compile:runMain) Nonzero exit code: 1
[error] Total time: 0 s, completed Jan 17, 2016 5:35:07 AM
```

**Comment by paulp** [comment]
Fixed in d0ebd2babe, thanks a lot. The benchmark is now run with the test suite as well.
